---
title: "Long Response 1: Case Studies"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Format

Length: 3-5 pages, 12 point font, double spaced.

## Overview

In this first long response assignment, you will select and study one data-driven decision system. For the purpose of this assignment, we define an data-driven decision system as a system or process that uses computation and data to make automated predictions and decisions about individual people or groups of people. For example, although Newton's method is an algorithm, it is not in itself an data-driven decision system. Some examples that would be appropriate include recommendation systems used by technology and social media companies, diagnostic algorithms used in medicine, or predictive screening tools used in education and by the police.

In your response, you will briefly describe the design and purpose of your data-driven decision system, explain how it relates to ideas discussed in class, and identify potential ethical concerns related to its use. Your response should be concise, precise, and accessible to a general audience.

Your long response should take the form of a brief blog post or encyclopedia article designed to introduce your chosen algorithm to an audience of your peers. Imagine that as a class, we are constructing a field guide/encyclopedia/guidebook that could be used as a reference for anyone interested in learning about algorithms in use today. After submitting your response, you will be assigned to edit one or two of your peers' responses

## Instructions

1.  Identify a decision system for your assignment and compile references you can draw on for your long response.

2.  Your long response should include the following sections:

    -   **Introduction (2 points):** Introduce your decision system. What purpose does it serve? Who created it? Who are its users? Who are its subjects?
    -   **Overview of algorithm (3 points):** What, if any, algorithms/automated systems are involved? Why do these satisfy the definition of algorithm? What are the inputs and outputs?
    -   **Technical information (2 points):** Explain how the algorithms work. If technical details are unavailable, explain why they are unavailable and to the best of your ability, use available information to explain how such algorithms typically work.
    -   **Ethical issues (3 points):** Identify potential ethical concerns and harms related to your decision system. For each ethical concern/harm raised, be sure to identify potential remedies if there are any.

3.  Finally, your long response will also be graded on the following criterion:

    -   **Presentation/exposition (3 points):** Submissions should be carefully edited with minimal typos/grammatical mistakes. Citations should be provided for all resources used.

4.  After submitting your response, you will be assigned to edit one of your peers' entries. Your edits will also be graded:

    -   **Comments (1 point)**: Provide constructive feedback---which parts require clarifying or editing? Are there issues that the writer should also consider?

    -   **Discussion questions (1 point)**: Write at least one discussion question for the writer and provide your own answer.
