---
title: "Long Response 1: Case Studies"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Format

Length: 3-5 pages, 12 point font, double spaced.

## Overview

In this first long response assignment, you will select and study one data-driven decision-making system. For the purpose of this assignment, we define an data-driven decision-making system as a system or process that uses computation and data to make automated predictions or decisions about individual people or groups of people. For example, although Newton's method is an algorithm, it is not in itself an data-driven decision system. Some examples that would be appropriate include recommendation systems used by technology and social media companies, diagnostic algorithms used in medicine, or predictive screening tools used in education and by police.

Imagine that as a class, we are constructing a field guide/encyclopedia/guidebook that could be used as a reference for anyone interested in learning about algorithms in use today. In your response, you will briefly describe the design and purpose of your data-driven decision-making system, explain how it relates to ideas discussed in class, and identify potential ethical concerns related to its use. Your response should be concise, precise, and accessible to a general audience.

Your long response should take the form of a brief blog post or encyclopedia article designed to introduce your topic to an audience of your peers.

## Instructions

1.  Identify a decision-making system for your assignment and compile references you can draw on for your long response.

2.  Your long response should include the following sections. Your response will be graded on your ability to cover the material outlined below in a clear, precise, and complete manner.

    -   **Introduction and background (4 points):** Introduce your decision-making system and relevant background information. Who created it and what purpose does it serve? Who are its users? Who are its subjects? How were decisions made before implementing this system? Are there related data-driven decision-making systems that we should know about?
    -   **How it works (4 points):** Explain how your chosen example works. What are the inputs and outputs? If technical details are unavailable, explain why they are unavailable and to the best of your ability, use available information to explain how such algorithms typically work.
    -   **Ethical issues (4 points):** Identify potential ethical concerns and harms related to your decision-making system. If there are harms associated with your decision-making system, who is affected? Be sure to discuss potential causes.
    -   **Remedies and conclusions (4 points):** For each ethical concern/harm raised, be sure to identify potential remedies if there are any. What do you think should be done? Provide a clear set of suggestions.

3.  Finally, your long response will also be graded on the following criterion:

    -   **Presentation/exposition (4 points):** Submissions should be carefully edited with minimal typos/grammatical mistakes. Citations should be provided for all resources used.

4.  For **extra credit**, you may find a partner in the class and peer edit each other's responses. In addition to the final drafts of your long responses, each of you should submit both the initial version of **your paper, with your partner's comments** as well as the initial version of **your partner's paper, with your comments.** In order to receive extra credit, you must seriously engage with your partner's writing and their suggestions for your paper. Simply completing the requirements is not enough.

    -   **Comments (0.5 point extra credit)**: Provide constructive feedback---which parts require clarifying or editing? In addition to line edits, you should provide a written summary of your feedback including at least two substantive critiques/suggestions for improvement.

    -   **Edits (0.5 point extra credit)**: Respond to and/or incorporate your partner's suggestions.
