---
title: "Long Response 3: Forms of Resistance"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Format

Length: 3-5 pages, 12 point font, double spaced.

## Overview

When ethical concerns arise as a result of algorithmic decision-making systems, how can we respond? In this long response assignment, you will select and study one remedy or form of resistance to algorithmic decision-making. Some examples to consider:

-   Regulation via legislation
-   Consumer boycotts
-   Worker-led organizing (ex. walkouts)
-   Algorithmic fairness research

In your long response, you should outline your chosen form of resistance, identify actual examples where it has been applied or use cases for which it has been developed, and discuss when and where it could be an effective response to abuses of algorithmic decision-making. You may choose to focus your attention on algorithms used in one domain. For example, you could choose to focus on regulation of algorithms used in the insurance industry or on boycotts of social media companies. Submissions should be thoroughly researched, with reference to high-quality sources. Submissions will be graded based on completeness, clarity, and depth.

## Instructions

1.  Your long response should discuss the following areas:

    -   **Introduction (3 points):** Introduce and define your form of resistance. Who are the main actors or participants?
    -   **Historical examples (3 points):** Identify at least two examples where your form of resistance has been used to respond to algorithmic decision-making and discuss whether it was effective.
    -   **Possibilities (3 points):** What kind of ethical concerns can be addressed via your selected form of resistance? Identify ways in which your selected form of resistance could be effective.
    -   **Shortcomings (3 points):** What kind of ethical concerns cannot be addressed via your selected form of resistance? Identify ways in which your selected form of resistance may not address all possible concerns?

2.  Finally, your long response will also be graded on the following criterion:

    -   **Presentation/exposition (3 points):** Submissions should be carefully edited, with citations for all resources used.
