project:
  type: website
  output-dir: docs

website:
  title: "STAT303"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - syllabus.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    mainfont: Work Sans

editor: visual

