project:
  type: website
  output-dir: docs

website:
  title: "STAT303"
  navbar:
    background: "#4b2e83"
    left:
      - syllabus.qmd
      - readings.qmd
      - assignments.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    mainfont: Work Sans

editor: visual

