---
title: "Readings"
---

+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| Date  | Readings                                                                                                                                                                                                                                                                                                                                                                 | Due                 |
+=======+==========================================================================================================================================================================================================================================================================================================================================================================+=====================+
| 9/29  | Allen Institute for AI. *Ask Delphi*. 2021, <https://delphi.allenai.org/>.                                                                                                                                                                                                                                                                                               |                     |
|       |                                                                                                                                                                                                                                                                                                                                                                          |                     |
|       | Bonde, Sheila, and Paul Firenze. *A Framework for Making Ethical Decisions*. May 2013, <https://www.brown.edu/academics/science-and-technology-studies/framework-making-ethical-decisions>.                                                                                                                                                                              |                     |
|       |                                                                                                                                                                                                                                                                                                                                                                          |                     |
|       | Gupta, Abhishek, and Victoria Heath. "AI Ethics Groups Are Repeating One of Society's Classic Mistakes." *MIT Technology Review*, Sept. 2020, <https://www.technologyreview.com/2020/09/14/1008323/ai-ethics-representation-artificial-intelligence-opinion/>.                                                                                                           |                     |
|       |                                                                                                                                                                                                                                                                                                                                                                          |                     |
|       | Jiang, Liwei. "Towards Machine Ethics and Norms." *AI2 Blog*, 4 Nov. 2021, <https://medium.com/ai2-blog/towards-machine-ethics-and-norms-d64f2bdde6a3>.                                                                                                                                                                                                                  |                     |
|       |                                                                                                                                                                                                                                                                                                                                                                          |                     |
|       | Raji, Deborah. "That's Not Fair!" *XRDS: Crossroads, The ACM Magazine for Students*, vol. 25, no. 3, Apr. 2019, pp. 44--48. *Spring 2019*, <https://doi.org/10.1145/3313127>.                                                                                                                                                                                            |                     |
+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| 10/4  | ACLU of Washington. "Automated Decision Making Systems Are Making Some of the Most Important Life Decisions For You, but You Might Not Even Know It." *ACLU of Washington*, 22 Sept. 2021, <https://www.aclu-wa.org/story/automated-decision-making-systems-are-making-some-most-important-life-decisions-you-you-might>.                                                |                     |
|       |                                                                                                                                                                                                                                                                                                                                                                          |                     |
|       | Kearns, Michael, and Aaron Roth. "Introduction." *The Ethical Algorithm: The Science of Socially Aware Algorithm Design*, Oxford University Press USA - OSO, 2019. *ProQuest Ebook Central*, <http://ebookcentral.proquest.com/lib/washington/detail.action?docID=5905172>.                                                                                              |                     |
|       |                                                                                                                                                                                                                                                                                                                                                                          |                     |
|       | Lum, Kristian, and Rumman Chowdhury. "What Is an 'Algorithm'? It Depends Whom You Ask." *MIT Technology Review*, Feb. 2021, <https://www.technologyreview.com/2021/02/26/1020007/what-is-an-algorithm/>.                                                                                                                                                                 |                     |
+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| 10/6  | Bembeneck, Emily, et al. "To Stop Algorithmic Bias, We First Have to Define It." *Brookings*, 21 Oct. 2021, <https://www.brookings.edu/research/to-stop-algorithmic-bias-we-first-have-to-define-it/>.                                                                                                                                                                   |                     |
|       |                                                                                                                                                                                                                                                                                                                                                                          |                     |
|       | Benjamin, Ruha. "Default Discrimination." *Race after Technology: Abolitionist Tools for the New Jim Code*, Polity Press, 2019. *ProQuest Ebook Central*, <http://ebookcentral.proquest.com/lib/washington/detail.action?docID=5820427>.                                                                                                                                 |                     |
|       |                                                                                                                                                                                                                                                                                                                                                                          |                     |
|       | Chowdhury, Rumman. *Sharing Learnings about Our Image Cropping Algorithm*. 19 May 2021, <https://blog.twitter.com/engineering/en_us/topics/insights/2021/sharing-learnings-about-our-image-cropping-algorithm>.                                                                                                                                                          |                     |
|       |                                                                                                                                                                                                                                                                                                                                                                          |                     |
|       | Friedman, Batya, and Helen Nissenbaum. "Bias in Computer Systems." *ACM Transactions on Information Systems*, vol. 14, no. 3, July 1996, pp. 330--47. *July 1996*, <https://doi.org/10.1145/230538.230561>.                                                                                                                                                              |                     |
|       |                                                                                                                                                                                                                                                                                                                                                                          |                     |
|       | Vox. *Are We Automating Racism?* 2021. *YouTube*, <https://www.youtube.com/watch?v=Ok5sKLXqynQ>.                                                                                                                                                                                                                                                                         |                     |
+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| 10/11 | Feathers, Todd. *Police Are Telling ShotSpotter to Alter Evidence From Gunshot-Detecting AI*. 26 July 2021, <https://www.vice.com/en/article/qj8xbq/police-are-telling-shotspotter-to-alter-evidence-from-gunshot-detecting-ai>.                                                                                                                                         |                     |
|       |                                                                                                                                                                                                                                                                                                                                                                          |                     |
|       | Mitchell, Shira, et al. "Algorithmic Fairness: Choices, Assumptions, and Definitions." *Annual Review of Statistics and Its Application*, vol. 8, no. 1, 2021, p. null. *Annual Reviews*, <https://doi.org/10.1146/annurev-statistics-042720-125902>.                                                                                                                    |                     |
|       |                                                                                                                                                                                                                                                                                                                                                                          |                     |
|       | Smith, Ben. "How TikTok Reads Your Mind." *The New York Times*, 6 Dec. 2021. *NYTimes.com*, <https://www.nytimes.com/2021/12/05/business/media/tiktok-algorithm.html>.                                                                                                                                                                                                   |                     |
+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| 10/13 | Jeffries, Adrianne, et al. "Swinging the Vote?" *The Markup*, Feb. 2020, <https://themarkup.org/google-the-giant/2020/02/26/wheres-my-email>.                                                                                                                                                                                                                            |                     |
|       |                                                                                                                                                                                                                                                                                                                                                                          |                     |
|       | Kirchner, Lauren. "Powerful DNA Software Used in Hundreds of Criminal Cases Faces New Scrutiny." *The Markup*, Mar. 2021, <https://themarkup.org/news/2021/03/09/powerful-dna-software-used-in-hundreds-of-criminal-cases-faces-new-scrutiny>.                                                                                                                           |                     |
|       |                                                                                                                                                                                                                                                                                                                                                                          |                     |
|       | \-\--. "When Zombie Data Costs You a Home." *The Markup*, Oct. 2020, <https://themarkup.org/locked-out/2020/10/06/zombie-criminal-records-housing-background-checks>.                                                                                                                                                                                                    |                     |
|       |                                                                                                                                                                                                                                                                                                                                                                          |                     |
|       | Varner, Maddy, and Aaron Sankin. "Suckers List: How Allstate's Secret Auto Insurance Algorithm Squeezes Big Spenders." *The Markup*, Feb. 2020, <https://themarkup.org/allstates-algorithm/2020/02/25/car-insurance-suckers-list>.                                                                                                                                       |                     |
+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| 10/18 | Fry, Hannah. "What Statistics Can and Can't Tell Us About Ourselves." *The New Yorker*, Sept. 2019, <https://www.newyorker.com/magazine/2019/09/09/what-statistics-can-and-cant-tell-us-about-ourselves>.                                                                                                                                                                |                     |
|       |                                                                                                                                                                                                                                                                                                                                                                          |                     |
|       | Ochigame, Rodrigo. "The Long History of Algorithmic Fairness." *Phenomenal World*, 30 Jan. 2020, <https://phenomenalworld.org/analysis/long-history-algorithmic-fairness>.                                                                                                                                                                                               |                     |
|       |                                                                                                                                                                                                                                                                                                                                                                          |                     |
|       | Onuoha, Mimi. "When Proof Is Not Enough." *FiveThirtyEight*, 1 July 2020, <https://fivethirtyeight.com/features/when-proof-is-not-enough/>.                                                                                                                                                                                                                              |                     |
|       |                                                                                                                                                                                                                                                                                                                                                                          |                     |
|       | Whitby, Andrew. "A Brief History of the Census---and How Covid-19 Could Change It." *Wired*, Apr. 2020. *www.wired.com*, <https://www.wired.com/story/brief-history-census-how-covid-19-could-change-it/>.                                                                                                                                                               |                     |
+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| 10/20 | Buolamwini, Joy, et al. *Facial Recognition Technologies: A Primer*. 29 May 2020, <https://global-uploads.webflow.com/5e027ca188c99e3515b404b7/5ed1002058516c11edc66a14_FRTsPrimerMay2020.pdf>.                                                                                                                                                                          |                     |
|       |                                                                                                                                                                                                                                                                                                                                                                          |                     |
|       | Hill, Kashmir, and Aaron Krolik. "How Photos of Your Kids Are Powering Surveillance Technology." *The New York Times*, 11 Oct. 2019. *NYTimes.com*, <https://www.nytimes.com/interactive/2019/10/11/technology/flickr-facial-recognition.html>.                                                                                                                          |                     |
|       |                                                                                                                                                                                                                                                                                                                                                                          |                     |
|       | McVean, Ada. "40 Years of Human Experimentation in America: The Tuskegee Study." *Office for Science and Society*, 25 Jan. 2019, <https://www.mcgill.ca/oss/article/history/40-years-human-experimentation-america-tuskegee-study>.                                                                                                                                      |                     |
+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| 10/25 | Buolamwini, Joy, and Timnit Gebru. "Gender Shades: Intersectional Accuracy Disparities in Commercial Gender Classification." *Conference on Fairness, Accountability and Transparency*, PMLR, 2018, pp. 77--91. *proceedings.mlr.press*, <http://proceedings.mlr.press/v81/buolamwini18a.html>.                                                                          |                     |
|       |                                                                                                                                                                                                                                                                                                                                                                          |                     |
|       | Castelvecchi, Davide. "Is Facial Recognition Too Biased to Be Let Loose?" *Nature*, vol. 587, no. 7834, 7834, Nature Publishing Group, Nov. 2020, pp. 347--49. *www.nature.com*, <https://doi.org/10.1038/d41586-020-03186-4>.                                                                                                                                           |                     |
|       |                                                                                                                                                                                                                                                                                                                                                                          |                     |
|       | MIT Media Lab. *Gender Shades*. 2018. *YouTube*, <https://www.youtube.com/watch?v=TWWsW1w-BVo>.                                                                                                                                                                                                                                                                          |                     |
|       |                                                                                                                                                                                                                                                                                                                                                                          |                     |
|       | Noorden, Richard Van. "The Ethical Questions That Haunt Facial-Recognition Research." *Nature*, vol. 587, no. 7834, 7834, Nature Publishing Group, Nov. 2020, pp. 354--58. *www.nature.com*, <https://doi.org/10.1038/d41586-020-03187-3>.                                                                                                                               |                     |
+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| 10/27 | Angwin, Julia, et al. "Machine Bias." *ProPublica*, 23 May 2016, <https://www.propublica.org/article/machine-bias-risk-assessments-in-criminal-sentencing?token=jRdnwabwdw5HLiHY-R3nqWS5DOjEM7W->.                                                                                                                                                                       |                     |
|       |                                                                                                                                                                                                                                                                                                                                                                          |                     |
|       | Hill, Kashmir. "Wrongfully Accused by an Algorithm." *The New York Times*, 24 June 2020. *NYTimes.com*, <https://www.nytimes.com/2020/06/24/technology/facial-recognition-arrest.html>.                                                                                                                                                                                  |                     |
|       |                                                                                                                                                                                                                                                                                                                                                                          |                     |
|       | Lum, Kristian, and William Isaac. "To Predict and Serve?" *Significance*, vol. 13, no. 5, 2016, pp. 14--19. *Wiley Online Library*, <https://doi.org/10.1111/j.1740-9713.2016.00960.x>.                                                                                                                                                                                  |                     |
|       |                                                                                                                                                                                                                                                                                                                                                                          |                     |
|       | O'Neill, James. "How Facial Recognition Makes You Safer." *The New York Times*, 9 June 2019. *NYTimes.com*, <https://www.nytimes.com/2019/06/09/opinion/facial-recognition-police-new-york-city.html>.                                                                                                                                                                   |                     |
+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| 11/1  | Arvind Narayanan. *Tutorial: 21 Fairness Definitions and Their Politics*. 2018. *YouTube*, <https://www.youtube.com/watch?v=jIXIuYdnyyk>.                                                                                                                                                                                                                                |                     |
|       |                                                                                                                                                                                                                                                                                                                                                                          |                     |
|       | Chouldechova, Alexandra. "Fair Prediction with Disparate Impact: A Study of Bias in Recidivism Prediction Instruments." *Big Data*, vol. 5, no. 2, Mary Ann Liebert, Inc., publishers, June 2017, pp. 153--63. *liebertpub.com (Atypon)*, <https://doi.org/10.1089/big.2016.0047>.                                                                                       |                     |
|       |                                                                                                                                                                                                                                                                                                                                                                          |                     |
|       | Mitchell, Shira, et al. "Algorithmic Fairness: Choices, Assumptions, and Definitions." *Annual Review of Statistics and Its Application*, vol. 8, no. 1, 2021, p. null. *Annual Reviews*, <https://doi.org/10.1146/annurev-statistics-042720-125902>.                                                                                                                    |                     |
+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| 11/3  | Crawford, Kate. "State." *The Atlas of AI*, Yale University Press, 2021, pp. 181--209. *JSTOR*, <https://doi.org/10.2307/j.ctv1ghv45t.9>.                                                                                                                                                                                                                                |                     |
|       |                                                                                                                                                                                                                                                                                                                                                                          |                     |
|       | Green, Ben. *The Innovative City: The Relationship between Technical and Nontechnical Change in City Government*. 2019. *direct.mit.edu*, <https://direct.mit.edu/books/book/4204/chapter/172388/The-Innovative-City-The-Relationship-between>.                                                                                                                          |                     |
+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| 11/8  | Ingold, David, and Spencer Soper. "Amazon Doesn't Consider the Race of Its Customers. Should It?" *Bloomberg.Com*, 21 Apr. 2016, <http://www.bloomberg.com/graphics/2016-amazon-same-day/>.                                                                                                                                                                              |                     |
|       |                                                                                                                                                                                                                                                                                                                                                                          |                     |
|       | MIT Technology Review. *Podcast: In Machines We Trust - Hired by an Algorithm*. 2021. *YouTube*, <https://www.youtube.com/watch?v=ztcVB_zh_M0>.                                                                                                                                                                                                                          |                     |
|       |                                                                                                                                                                                                                                                                                                                                                                          |                     |
|       | Raghavan, Manish, and Solon Barocas. "Challenges for Mitigating Bias in Algorithmic Hiring." *Brookings*, 6 Dec. 2019, <https://www.brookings.edu/research/challenges-for-mitigating-bias-in-algorithmic-hiring/>.                                                                                                                                                       |                     |
+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| 11/10 | Booth, Robert. "Uber Drivers to Launch Legal Bid to Uncover App's Algorithm." *The Guardian*, 20 July 2020, <http://www.theguardian.com/technology/2020/jul/20/uber-drivers-to-launch-legal-bid-to-uncover-apps-algorithm>.                                                                                                                                              |                     |
|       |                                                                                                                                                                                                                                                                                                                                                                          |                     |
|       | Crawford, Kate. "Labor." *The Atlas of AI*, Yale University Press, 2021, pp. 53--87. *JSTOR*, <https://doi.org/10.2307/j.ctv1ghv45t.5>.                                                                                                                                                                                                                                  |                     |
|       |                                                                                                                                                                                                                                                                                                                                                                          |                     |
|       | Gurley, Lauren Kaori. "Amazon Drivers Are Instructed to Drive Recklessly to Meet Delivery Quotas." *VICE*, 6 May 2021, <https://www.vice.com/en/article/xgxx54/amazon-drivers-are-instructed-to-drive-recklessly-to-meet-delivery-quotas>.                                                                                                                               |                     |
|       |                                                                                                                                                                                                                                                                                                                                                                          |                     |
|       | The Financial Times. *The Uber Game*. 2020, <https://ig.ft.com/uber-game>.                                                                                                                                                                                                                                                                                               |                     |
+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| 11/15 | Eubanks, Virginia. "A Child Abuse Prediction Model Fails Poor Families." *Wired*, Jan. 2018. *www.wired.com*, <https://www.wired.com/story/excerpt-from-automating-inequality/>.                                                                                                                                                                                         |                     |
|       |                                                                                                                                                                                                                                                                                                                                                                          |                     |
|       | Gilman, Michele. *Poverty Lawgorithms*. Data & Society, 15 Sept. 2020, <https://datasociety.net/library/poverty-lawgorithms/>.                                                                                                                                                                                                                                           |                     |
|       |                                                                                                                                                                                                                                                                                                                                                                          |                     |
|       | Henriques-Gomes, Luke. "The Automated System Leaving Welfare Recipients Cut off with Nowhere to Turn." *The Guardian*, 16 Oct. 2019, <http://www.theguardian.com/technology/2019/oct/16/automated-messages-welfare-australia-system>.                                                                                                                                    |                     |
|       |                                                                                                                                                                                                                                                                                                                                                                          |                     |
|       | Sudhir, K., and Shyam Sunder. "What Happens When a Billion Identities Are Digitized?" *Yale Insights*, 27 Mar. 2020, <https://insights.som.yale.edu/insights/what-happens-when-billion-identities-are-digitized>.                                                                                                                                                        |                     |
+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| 11/17 | Chen, Irene Y., et al. "Ethical Machine Learning in Healthcare." *Annual Review of Biomedical Data Science*, vol. 4, no. 1, 2021, p. null. *Annual Reviews*, <https://doi.org/10.1146/annurev-biodatasci-092820-114757>.                                                                                                                                                 |                     |
|       |                                                                                                                                                                                                                                                                                                                                                                          |                     |
|       | Obermeyer, Ziad, et al. "Dissecting Racial Bias in an Algorithm Used to Manage the Health of Populations." *Science*, vol. 366, no. 6464, American Association for the Advancement of Science, Oct. 2019, pp. 447--53. *www-science-org.offcampus.lib.washington.edu (Atypon)*, <https://doi.org/10.1126/science.aax2342>.                                               |                     |
+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| 11/22 | Jeffrey Mervis. "Can a Set of Equations Keep U.S. Census Data Private?" *ScienceInsider*, 4 Jan. 2019, <https://www.science.org/content/article/can-set-equations-keep-us-census-data-private>.                                                                                                                                                                          |                     |
|       |                                                                                                                                                                                                                                                                                                                                                                          |                     |
|       | Wezerek, Gus, and David Van Riper. "Opinion \| Changes to the Census Could Make Small Towns Disappear." *The New York Times*, 6 Feb. 2020. *NYTimes.com*, <https://www.nytimes.com/interactive/2020/02/06/opinion/census-algorithm-privacy.html>.                                                                                                                        |                     |
|       |                                                                                                                                                                                                                                                                                                                                                                          |                     |
|       | Wolford, Ben. "What Is GDPR, the EU's New Data Protection Law?" *GDPR.Eu*, 7 Nov. 2018, <https://gdpr.eu/what-is-gdpr/>.                                                                                                                                                                                                                                                 |                     |
|       |                                                                                                                                                                                                                                                                                                                                                                          |                     |
|       | Wood, Alexandra, et al. "Differential Privacy: A Primer for a Non-Technical Audience." *Vanderbilt Journal of Entertainment & Technology Law*, vol. 21, no. 1, 2018, pp. 209--75.                                                                                                                                                                                        |                     |
+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| 11/24 | NO CLASS                                                                                                                                                                                                                                                                                                                                                                 |                     |
+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| 11/29 | Green, Ben. "The False Promise of Risk Assessments: Epistemic Reform and the Limits of Fairness." *Proceedings of the 2020 Conference on Fairness, Accountability, and Transparency*, Association for Computing Machinery, 2020, pp. 594--606. *ACM Digital Library*, <https://doi.org/10.1145/3351095.3372869>.                                                         |                     |
|       |                                                                                                                                                                                                                                                                                                                                                                          |                     |
|       | Hooker, Sara. "Moving beyond 'Algorithmic Bias Is a Data Problem.'" *Patterns*, vol. 2, no. 4, Elsevier, Apr. 2021. *www.cell.com*, <https://doi.org/10.1016/j.patter.2021.100241>.                                                                                                                                                                                      |                     |
|       |                                                                                                                                                                                                                                                                                                                                                                          |                     |
|       | Raji, Inioluwa Deborah, and Joy Buolamwini. "Actionable Auditing: Investigating the Impact of Publicly Naming Biased Performance Results of Commercial AI Products." *Proceedings of the 2019 AAAI/ACM Conference on AI, Ethics, and Society*, Association for Computing Machinery, 2019, pp. 429--35. *ACM Digital Library*, <https://doi.org/10.1145/3306618.3314244>. |                     |
|       |                                                                                                                                                                                                                                                                                                                                                                          |                     |
|       | Upchurch, Tom. "To Work for Society, Data Scientists Need a Hippocratic Oath with Teeth." *Wired UK*. *www.wired.co.uk*, <https://www.wired.co.uk/article/data-ai-ethics-hippocratic-oath-cathy-o-neil-weapons-of-math-destruction>. Accessed 10 May 2021.                                                                                                               |                     |
+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| 12/1  | Campbell, Alexia Fernndez. "How Tech Employees Are Pushing Silicon Valley to Put Ethics before Profit." *Vox*, Oct. 2018, <https://www.vox.com/technology/2018/10/18/17989482/google-amazon-employee-ethics-contracts>.                                                                                                                                                 |                     |
|       |                                                                                                                                                                                                                                                                                                                                                                          |                     |
|       | Heilweil, Rebecca. "Facebook Is Taking a Hard Look at Racial Bias in Its Algorithms." *Vox*, July 2020, <https://www.vox.com/recode/2020/7/22/21334051/facebook-news-feed-instagram-algorithm-racial-bias-civil-rights-audit>.                                                                                                                                           |                     |
|       |                                                                                                                                                                                                                                                                                                                                                                          |                     |
|       | Mullainathan, Sendhil. "Biased Algorithms Are Easier to Fix Than Biased People." *The New York Times*, 6 Dec. 2019. *NYTimes.com*, <https://www.nytimes.com/2019/12/06/business/algorithm-bias-fix.html>.                                                                                                                                                                |                     |
|       |                                                                                                                                                                                                                                                                                                                                                                          |                     |
|       | NIckelsburg, Monica. "Washington State Lawmakers Seek to Ban Government from Using Discriminatory AI Tech." *GeekWire*, Feb. 2021, <https://www.geekwire.com/2021/washington-state-lawmakers-seek-ban-government-using-ai-tech-discriminates/>.                                                                                                                          |                     |
|       |                                                                                                                                                                                                                                                                                                                                                                          |                     |
|       | Richardson, Rashida. *Confronting Black Boxes: A Shadow Report of the New York City Automated Decision System Task Force*. AI Now Institute, 4 Dec. 2019, [https:// ainowinstitute.org/ads-shadowreport-2019.html](https://ainowinstitute.org/ads-shadowreport-2019.html).                                                                                               |                     |
+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| 12/6  |                                                                                                                                                                                                                                                                                                                                                                          | Final Presentations |
+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| 12/8  |                                                                                                                                                                                                                                                                                                                                                                          | Final Presentations |
+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
