---
title: "Readings"
bibliography: references.bib
fontsize: .85em
format: 
  pdf: default
---

+-------+---------------------------------+-------------------------------+------------------------------+---------------------+
| Date  | Topic                           | Required readings             | Optional                     | Due                 |
+=======+=================================+===============================+==============================+=====================+
| 9/29  | *Introduction*                  | -   @alleninstituteforai2021  | -   @raji_thats_2019         |                     |
|       |                                 | -   @bonde2013                |                              |                     |
|       |                                 | -   @gupta2020                |                              |                     |
|       |                                 | -   @jiang2021                |                              |                     |
+-------+---------------------------------+-------------------------------+------------------------------+---------------------+
| 10/4  | *Algorithmic decision making*   | -   @acluofwashington2021     |                              |                     |
|       |                                 | -   @kearns2019               |                              |                     |
|       |                                 | -   @lum_what_2021            |                              |                     |
|       |                                 | -   @stabilityai              |                              |                     |
|       |                                 | -   @baio2022                 |                              |                     |
+-------+---------------------------------+-------------------------------+------------------------------+---------------------+
| 10/6  | *What is algorithmic bias?*     | -   @bembeneck2021            | -   @friedman1996            |                     |
|       |                                 | -   @benjamin2019             |                              |                     |
|       |                                 | -   @chowdhury2021            |                              |                     |
|       |                                 | -   @vox2021                  |                              |                     |
+-------+---------------------------------+-------------------------------+------------------------------+---------------------+
| 10/11 | *Identifying algorithmic harms* | -   @jeffries2020             |                              |                     |
|       |                                 | -   @kirchner2021             |                              |                     |
|       |                                 | -   @kirchner_when_2020       |                              |                     |
|       |                                 | -   @varner2020               |                              |                     |
+-------+---------------------------------+-------------------------------+------------------------------+---------------------+
| 10/13 | *Algorithmic fairness*          | -   @feathers2021             |                              |                     |
|       |                                 | -   @mitchell2021             |                              |                     |
|       |                                 | -   @smith2021                |                              |                     |
+-------+---------------------------------+-------------------------------+------------------------------+---------------------+
| 10/18 | *Ethics of data collection*     | -   @mcvean2019               | -   @ochigame2020            |                     |
|       |                                 | -   @whitby2020               |                              |                     |
|       |                                 | -   @onuoha2020               |                              |                     |
+-------+---------------------------------+-------------------------------+------------------------------+---------------------+
| 10/20 | *Facial recognition*            | -   @buolamwini2020           | -   @castelvecchi2020        |                     |
|       |                                 |                               | -   @noorden2020             |                     |
|       |                                 | -   @hill2019                 |                              |                     |
|       |                                 |                               |                              |                     |
|       |                                 | -   @buolamwini2018           |                              |                     |
|       |                                 |                               |                              |                     |
|       |                                 | -   @mitmedialab2018          |                              |                     |
+-------+---------------------------------+-------------------------------+------------------------------+---------------------+
| 10/25 | *Criminal Justice*              | -   @angwin2016               |                              |                     |
|       |                                 | -   @hill2020                 |                              |                     |
|       |                                 | -   @lum_predict_2016         |                              |                     |
|       |                                 | -   @oneill2019               |                              |                     |
+-------+---------------------------------+-------------------------------+------------------------------+---------------------+
| 10/27 | *Quantifying fairness*          | -   @chouldechova2017         | -   @arvindnarayanan2018     |                     |
|       |                                 | -   @mitchell2021             |                              |                     |
+-------+---------------------------------+-------------------------------+------------------------------+---------------------+
| 11/1  | *Quantifying fairness*          | -   @rudin2020                |                              |                     |
|       |                                 | -   @chouldechova2020         |                              |                     |
|       |                                 | -   @jackson2020              |                              |                     |
+-------+---------------------------------+-------------------------------+------------------------------+---------------------+
| 11/3  | *Public algorithms*             | -   @crawford2021             |                              |                     |
|       |                                 | -   @green_innovative_2019    |                              |                     |
+-------+---------------------------------+-------------------------------+------------------------------+---------------------+
| 11/8  | *Private algorithms*            | -   @ingold2016               | -   @mittechnologyreview2021 |                     |
|       |                                 | -   @raghavan2019             |                              |                     |
+-------+---------------------------------+-------------------------------+------------------------------+---------------------+
| 11/10 | *Labor*                         | -   @booth2020                |                              |                     |
|       |                                 | -   @crawford2021             |                              |                     |
|       |                                 | -   @gurley2021               |                              |                     |
|       |                                 | -   @thefinancialtimes2020    |                              |                     |
+-------+---------------------------------+-------------------------------+------------------------------+---------------------+
| 11/15 | *Welfare*                       | -   @eubanks2018              | -   @gilman2020              |                     |
|       |                                 | -   @henriques-gomes2019      |                              |                     |
|       |                                 | -   @sudhir2020               |                              |                     |
+-------+---------------------------------+-------------------------------+------------------------------+---------------------+
| 11/17 | *Healthcare*                    | -   @chen2021                 |                              |                     |
|       |                                 | -   @obermeyer2019            |                              |                     |
+-------+---------------------------------+-------------------------------+------------------------------+---------------------+
| 11/22 | *Privacy*                       | -   @jeffrey_mervis_can_2019  | -                            |                     |
|       |                                 | -   @wezerek2020              |                              |                     |
|       |                                 | -   @wolford2018              |                              |                     |
|       |                                 | -   @wood2018                 |                              |                     |
+-------+---------------------------------+-------------------------------+------------------------------+---------------------+
| 11/24 |                                 | NO CLASS                      |                              |                     |
+-------+---------------------------------+-------------------------------+------------------------------+---------------------+
| 11/29 | *Paths forward*                 | -   @green_false_2020         |                              |                     |
|       |                                 | -   @hooker2021               |                              |                     |
|       |                                 | -   @raji2019                 |                              |                     |
|       |                                 | -   @upchurch2018             |                              |                     |
+-------+---------------------------------+-------------------------------+------------------------------+---------------------+
| 12/1  | *Paths forward*                 | -   @mullainathan_biased_2019 |                              |                     |
|       |                                 | -   @campbell2018             |                              |                     |
|       |                                 | -   @heilweil2020             |                              |                     |
|       |                                 | -   @nickelsburg2021          |                              |                     |
|       |                                 | -   @richardson2019           |                              |                     |
+-------+---------------------------------+-------------------------------+------------------------------+---------------------+
| 12/6  |                                 |                               |                              | Final Presentations |
+-------+---------------------------------+-------------------------------+------------------------------+---------------------+
| 12/8  |                                 |                               |                              | Final Presentations |
+-------+---------------------------------+-------------------------------+------------------------------+---------------------+
